### ISSUE TITLE
Does the "Current price..." triggers work properly?

### ISSUE THREAD

**Issue by TheArcturian** [slasktrat/com.tibber#10]
Does these triggers actually work?:

_Current price is at the lowest among the next [x] hours
Current price is at the highest among the next [x] hours
Current price is [x] percent below average of the next [y] hours
Current price is [x] percent above average of the next [y] hours_

I'm trying to create a flow that triggers during the two peaks during a day, the one in the morning usually between 7 and 11 and the one in the evening usually between around 15 and 20.

However whatever I try to set in the triggers above, it doesn't seem to trigger when it actually should and is usually too late or triggers when it shouldn't have triggered (low price).

Do you use these triggers yourself and can show an example that actually manage to trigger only the 3-4 hours in the morning and 4-5 hours in the evening when the price peaks? My goal is to turn off electric ovens and water boilers at those peaks and save a good sum of money each day that way (and still have hot water and enough warm air for comfort). Now these triggers doesn't seem to work properly.

![img_2991](https://user-images.githubusercontent.com/16746633/52977302-0feccc00-33cd-11e9-8a5b-ad6de9e7235e.PNG)

Values I use is 
"Current price is at the highest among the next [1] hours"
"Current price is at the highest among the next [3] hours"
"Current price is [2] percent above average of the next [3] hours"
"Current price is [5] percent above average of the next [1] hours"
etc.

Whatever I try of values, it doesn't seem to do a difference as it triggers way too frequent and too late.

**Comment by TheArcturian** [comment]
![skjermbilde](https://user-images.githubusercontent.com/16746633/52977395-6f4adc00-33cd-11e9-9957-dd5e8fbb42b4.PNG)

Peaks that I want the app to trigger is marked in the picture above.

**Comment by slasktrat** [comment]
Hi. Yes, I do use them myself and they should be working properly. However, "Current price is at the highest among the next [1] hours" will trigger every hour, use minimum 2 hours to get current + next.

To get a trigger at the marked point, you should use "Current price is at the lowest among the next [3] hours", but without any extra conditions it will in this case trigger every hour from 04:00 - 07:00.

**Comment by TheArcturian** [comment]
Okay, thanks for your input. However at 22:00 today (19.2.) I still get the "Current price is at the highest among the next [2] hours". If you check in Tibber, it really should not trigger at that point.

Also the "Current price is [1] percent above average of the next [2] hours" is triggered at 22:00. I cant see how the next 2 hours at that time can be above average at that time.

Can it be something wrong with the app?  (I'm still using Homey version 1.5.13).
What exactly triggers are you using?

**Comment by TheArcturian** [comment]
I have another trigger "Current price is [1] percent below average of the next [2] hours" running at the same time which I expected to be triggered at 22:00. Maybe the **average value** is calculated wrong in the app?

**Comment by slasktrat** [comment]
It sounds correct to me? 

I have the following prices in Tibber. 22:00 = 56.4, 23:00 = 55.9, 00:00 = 55.8. So current price @ 22:00 is at the highest among the next 2 hours. Not quite (almost) 1 percent above avg of the next 2 hours, but you might have slightly different prices than me?

**Comment by TheArcturian** [comment]
Ah, I thought the average was based on the whole day, all 24 hours.

So what do you recommend to configure to spot the two daily peaks precisely and before they peak?

**Comment by slasktrat** [comment]
Ok :) It does not, but maybe I will create such triggers as well.

I use longer periods in my triggers. "Above average of the next 8 hours" e.g. And it seems that would have triggered exactly the way you look for in both peaks in this chart. So maybe try with something like that?

**Comment by TheArcturian** [comment]
Okay, I'll try that and see if it helps.

If it is possible, it would be really great if you created two new triggers that looked like this:

**Current price is [x] percent above todays average
Current price is [x] percent below todays average**

where today is the average of all 24 hours of the day. I think that would make the triggers precise and perfect for whatever scenario of the prices each day. I hope that is possible to do and that you take time to do it. Thanks for your feedbacks! :-)

**Comment by TheArcturian** [comment]
I just saw 1.0.6 arrived on Homey. Is there any chance you will implement the two triggers for 1.0.7? :)

**Comment by slasktrat** [comment]
1.0.6 was submitted to the app store a week ago, but Homey has been slow to approve new apps lately. I guess they have been busy with the new flow editor :) But yes, I will try to include those in the next update.

**Comment by TheArcturian** [comment]
Yeah, good stuff that they came up with that one. :-)

Excellent! Really looking forward to the next update. Keep up your awesome work!

**Comment by slasktrat** [comment]
Implemented in 1.0.7:
